resolver: lts-18.1

extra-deps:
  # At the time of writing, no snapshot includes Clash 1.4 yet so we add it - and
  # its dependencies - manually.
  - lazysmallcheck-0.6
  - Stream-0.4.7.2
  - arrows-0.4.4.2
  - clash-prelude-1.4.2
  - clash-lib-1.4.2
  - clash-ghc-1.4.2
  # Required for liquid haskell
  - liquid-base-4.15.0.0
  - liquidhaskell-0.8.10.2
  - liquid-ghc-prim-0.7.0

# Needed due to liquid haskell deps
# - Diff 0.4 : (<0.4)
# - optparse-applicative 0.16.1 (<0.16)
allow-newer: true
